// <auto-generated />
using Machine_test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Machine_test.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Machine_test.Models.CategoryMaster", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryMaster");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Electronic"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = " Footware"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = " Cometics"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Medicical"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "MobileAccesories"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = " shopping"
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Business"
                        });
                });

            modelBuilder.Entity("Machine_test.Models.ProductMaster", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("ProductMaster");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Price = 0L,
                            ProductName = "shopping"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Price = 0L,
                            ProductName = "Business"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Price = 0L,
                            ProductName = "Electronic"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Price = 0L,
                            ProductName = "Online"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            Price = 0L,
                            ProductName = "Online"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 7,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 8,
                            Price = 0L,
                            ProductName = "Cometics"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 9,
                            Price = 0L,
                            ProductName = "Medicical"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 10,
                            Price = 0L,
                            ProductName = "MobileAccesories"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 11,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 12,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 13,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 14,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 15,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 16,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 17,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 18,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 19,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 20,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 21,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 22,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 23,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 24,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 25,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 26,
                            Price = 0L,
                            ProductName = "Sports"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 27,
                            Price = 0L,
                            ProductName = "Sports"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
